### ISSUE TITLE
[Docs] Create documentation for each UI components

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#100]
# Features required : 
1. Screenshots of UI components
2. Code of the respective UI components

**Comment by ISHITA-ROY016** [comment]
I want to work on this under jwoc

**Comment by Roshaen** [comment]
Assigning you @ISHITA-ROY016

**Comment by shreyanka155** [comment]
I want to work on this under jwoc

**Comment by Roshaen** [comment]
Sure @shreyanka155 
Ping me on discord I'll explain to you the flow for documentation

**Comment by sarkartanmay393** [comment]
@Roshaen Is this still open?

**Comment by radar101** [comment]
I would like to work under this issue as a part of JWOC.

**Comment by tmsagarofficial** [comment]
Would love to work on this issue under jwoc ...... assign it to me whenever possible

**Comment by Roshaen** [comment]
Sure @tmsagarofficial 
Choose a ui component for which you want to add docs
I'll assign you by creating a new issues for that component
