### ISSUE TITLE
 Add animated navigation bar for light and dark mode

### ISSUE THREAD

**Issue by ashdude1401** [Clueless-Community/Spectrum-UI#113]
I would like to request the addition of a new feature: an animated navigation bar that supports both light and dark mode. The design for this feature can be found in this Figma file:

For light mode -
 [https://www.figma.com/file/Lhmy3Wlvdo1fQeYgmHp6Ry/animated-mobile-navigation-give-away?node-id=0%3A1&t=8UWmPxb6kYDBpQ6I-1](url)

For Dark Mode -
[https://www.figma.com/file/5qmXvL7Dm3v2pHi12FWnNe/Flutter-Ui?node-id=119%3A1260&t=hsgBoTbJQNNhFaut-1](url)

The navigation bar should smoothly transition between light and dark mode based on the user's system settings. It should also include support for icons, labels, and customizable colors.

This feature would be a great addition to the repository and would greatly enhance the user experience. Please let me know if you need any additional details or requirements for this feature.

screenshots

![image](https://user-images.githubusercontent.com/98846260/221109532-6bb71de3-ff5c-496f-bf00-ad143aead02f.png)

![image](https://user-images.githubusercontent.com/98846260/221109290-03710ebc-04ac-4545-a35a-effb7074a630.png)

**Comment by Uttkarsh-raj** [comment]
Hey, I would like to work on this issue. Can you please assign this issue to me.

**Comment by ashdude1401** [comment]
Sure ,I am assigning this issue to you @Uttkarsh-raj  . Best of luck .

**Comment by ashdude1401** [comment]
@Uttkarsh-raj send me a new pr
