### ISSUE TITLE
[App] Design Serach page

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#123]
Figma link - https://www.figma.com/file/5qmXvL7Dm3v2pHi12FWnNe/Flutter-Ui?node-id=133%3A1260&t=iUS8M6hftxb0xSQl-0

![Search](https://user-images.githubusercontent.com/58213083/222413184-935a6340-32d4-4499-82b3-4ccb24d18dfd.png)

**Comment by sarkartanmay393** [comment]
@Roshaen I would like to work this issue under JWOC

**Comment by Akashsri3bi** [comment]
@Roshaen I can look into this

**Comment by Roshaen** [comment]
@sarkartanmay393 this issue is already assigned to WOC participants
Sorry I used the wrong tag (JWOC) under it
Please check out the other issues

**Comment by Roshaen** [comment]
Assigning you @Akashsri3bi
