### ISSUE TITLE
[App] Implement About Page

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#124]
Figma link - https://www.figma.com/file/5qmXvL7Dm3v2pHi12FWnNe/Flutter-Ui?node-id=183%3A1410&t=iUS8M6hftxb0xSQl-0

![About](https://user-images.githubusercontent.com/58213083/222413593-073d1b01-d886-4481-878b-9bac423b6dba.png)

**Comment by Uttkarsh-raj** [comment]
I would like to work on this issue... can you assign this to me..
