### ISSUE TITLE
[Slider] Create Slider UI components

### ISSUE THREAD

**Issue by Bhavikk01** [Clueless-Community/Spectrum-UI#132]
Figma Link:- https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=140%3A41849&t=mCoQLdTZmYG8rTwI-0

**Comment by radar101** [comment]
I want to work on this issue under the JWOC.

**Comment by Bhavikk01** [comment]
> I want to work on this issue under the JWOC.

Sure assigning it to you
