### ISSUE TITLE
[PROGRESS BAR] Create Progress bar UI components

### ISSUE THREAD

**Issue by Bhavikk01** [Clueless-Community/Spectrum-UI#134]
Figma Link:- https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=152%3A60162&t=VEhHTa8C85SrPyM7-0

**Comment by Prateek556** [comment]
I want to work on this issue under JWOC please assign me

**Comment by radar101** [comment]
I want to work on this issue under JWOC.

**Comment by Bhavikk01** [comment]
> I want to work on this issue under JWOC.

Sorry but you are already assigned with other issue.
