### ISSUE TITLE
[SEGMENTED CONTROL] Create Segmented Control UI components

### ISSUE THREAD

**Issue by Bhavikk01** [Clueless-Community/Spectrum-UI#135]
Figma Link:- https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=140%3A41847&t=VEhHTa8C85SrPyM7-0

**Comment by Uttkarsh-raj** [comment]
Hey i am interested in this issue can you assign this to me..

**Comment by cschinmay777** [comment]
I am interested in working on this issue under woc.

**Comment by Bhavikk01** [comment]
> I am interested in working on this issue under woc.

Have already assigned an issue to you.

**Comment by Bhavikk01** [comment]
@Uttkarsh-raj  have assigned to you
