### ISSUE TITLE
[FILTER] Create Filter UI components

### ISSUE THREAD

**Issue by Bhavikk01** [Clueless-Community/Spectrum-UI#136]
Figma Link:- https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=140%3A42063&t=VEhHTa8C85SrPyM7-0

**Comment by Prateek556** [comment]
I want to work on this issue under JWOC

**Comment by cschinmay777** [comment]
I am interested in working on this issue under woc.

**Comment by Bhavikk01** [comment]
> I want to work on this issue under JWOC

Have already assigned one issue to you.
