### ISSUE TITLE
Add New Elevated Button Style

### ISSUE THREAD

**Issue by Jiggy9** [Clueless-Community/Spectrum-UI#145]
I would like to contribute to the all buttons folder by adding a new elevated button style. I have a fresh and unique design in mind that I believe will enhance the overall user experience.

as GSSoC'23 contribute I'll send PR and modify it.. I would appreciate it if you could assign me the task of implementing this new elevated button style.

**Comment by mridul45** [comment]
Greetings , I think my skills would be a good ally for the issue . As GSSOC 23 contributor I request you to assign me the issue .

**Comment by BhavaniSaranga12** [comment]
Hello, I can style the elevated button. I request you to assign me this issue.

**Comment by Apreksha** [comment]
Hello. I'm a GSSoC'23 contributor. I want to add new elevated button style. Could you please assign me this task.

**Comment by ashdude1401** [comment]
@Jiggy9 could you please share more info regarding your Idea and design or Figma file that you want to implement .

**Comment by Jiggy9** [comment]
Here's how it looks like after I added my new Elevated button style which is more user friendly compare to others.

<img width="201" alt="button8" src="https://github.com/Clueless-Community/Spectrum-UI/assets/112299754/81caa897-505d-4ac2-ab77-0f7d962fded1">

**Comment by ashdude1401** [comment]
Hi Jiggy,

I'm writing to you today to close the PR for the new button design. After careful review, we've decided that the new design is not a good fit for our app.

The main issue is that the new design is too similar to the existing design. The only changes are the color and padding, which is not enough to make the new design stand out. As a result, the new design would be confusing and disorienting for users.

We understand that you put a lot of work into the new design, and we appreciate your efforts. However, we believe that it is in the best interest of the app to go with a different design.

We will be providing a new button design to you within the next two days. In the meantime, please continue to find new bugs and enhancements in the app.

Thank you for your understanding.

Best regards,
