### ISSUE TITLE
login and sigin with firebase 

### ISSUE THREAD

**Issue by LegendSumeet** [Clueless-Community/Spectrum-UI#146]
i am gssoc contributor

**Comment by mridul45** [comment]
can you assign this to me, I want to work on this under GSSoC'23 . I think my skills would be a good math for this issue.

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant

**Comment by Apreksha** [comment]
Hello. I'm a GSSoC'23 contributor. I want to login and signin with firebase. Could you please assign me this task.

**Comment by ashdude1401** [comment]
Dear @LegendSumeet ,

Thank you for submitting your Pull Request regarding the login and sign-in functionality. After careful consideration, we have decided not to include these features in the app as they fall outside the primary scope of its functionalities.

We appreciate your effort in raising this issue and your dedication to improving the app. We encourage you to redirect your focus towards identifying other potential bugs or suggesting enhancements that align with the app's core objectives.

Once again, thank you for your contribution and your understanding. We look forward to your continued involvement in making our app even better.

Best regards,
Ashhtosh Jha/Spectrum UI
