### ISSUE TITLE
improving the ui in better ux

### ISSUE THREAD

**Issue by LegendSumeet** [Clueless-Community/Spectrum-UI#147]
can you assign this to me, I want to work on this under GSSoC'23

**Comment by Apreksha** [comment]
Hello. I'm a GSSoC'23 contributor. I want to improving the UI. Could you please assign me this task.

**Comment by ashdude1401** [comment]
@LegendSumeet could you please share more info regarding your Idea and design or Figma file that you want to implement .

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by ashdude1401** [comment]
> can you please assign me this issue under GSSoc 2023. I really want to work on this issue.
could you please share more info regarding your Idea and design or Figma file that you want to implement .

**Comment by Saksham0205** [comment]
@ashdude1401 change in text font, background color,  animations, enabling dark mode and many more

**Comment by LegendSumeet** [comment]
https://github.com/LegendSumeet/CodeHUBApp @ashdude1401 here is my work i can make ui user friendly

**Comment by Debajyoti14** [comment]
@Saksham0205 @LegendSumeet Your thoughts are appreciated, but we can only assign you if you explain implicitly what is the part you are going to work like- Animations in which section and with example which type of animation.

**Comment by LegendSumeet** [comment]
App Bar
Bottom Navigation Bar
Alerts
Calendars UI
Buttons 
these type of widgets and with a hero animation

**Comment by LegendSumeet** [comment]
@Debajyoti14

**Comment by Saksham0205** [comment]
@Debajyoti14  
1) more types of message notification alert like message box with 2-3 Solid colors in single box..
2) Parallax scrolling
