### ISSUE TITLE
adding the drawer to get all section in one place with better ux

### ISSUE THREAD

**Issue by LegendSumeet** [Clueless-Community/Spectrum-UI#148]
can you assign this to me, I want to work on this under GSSoC'23

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant
I am a flutter developer

**Comment by Apreksha** [comment]
Hello. I'm a GSSoC'23 contributor. I want to add drawer to get all section in one place with better UX. Could you please assign me this task.

**Comment by ashdude1401** [comment]
@LegendSumeet could you please share more info regarding your Idea and design or Figma file that you want to implement .

**Comment by aniket2125ec1117** [comment]
Hello i am GSSOC 23 contributer i can do this within 3 to 4 days

**Comment by ashdude1401** [comment]
@LegendSumeet we have a design system in our app , we can not just add on some component . We have check weather the component is matching to the app theme or not.   So , for now I closing this issue , you find some other bug or enhancement in the app. Most expectedly tomorrow we will be providing the new design system and we will raising the issue for the same  .So, till then stay tuned!.
