### ISSUE TITLE
adding the splashscreen 

### ISSUE THREAD

**Issue by LegendSumeet** [Clueless-Community/Spectrum-UI#149]
can you assign this to me, I want to work on this under GSSoC'23

**Comment by mridul45** [comment]
can you assign this to me, I want to work on this under GSSoC'23 . I think my skills would be a great match for the above isse.

**Comment by Naincy04** [comment]
Hello, I want to work on this issue under GSSoc'23. Can u please assign this to me?

**Comment by Apreksha** [comment]
Hello. I'm a GSSoC'23 contributor. I want to add splash screen feature. Could you please assign me this task.

**Comment by ashdude1401** [comment]
@LegendSumeet we already have splash screen .Please share more info regarding your Idea and design or Figma file that you want to implement  to proceed further .
