### ISSUE TITLE
Unresponsive cards

### ISSUE THREAD

**Issue by D-Aman-S** [Clueless-Community/Spectrum-UI#150]
The Cards are Unresponsive because of the improper constraints given to them, using expanded widgets should adequately fix them.
They overflow in devices with widths of 360 - 388 px and many phones still use this.

![image](https://github.com/Clueless-Community/Spectrum-UI/assets/75574963/facc32a1-a03d-4c39-8861-359ec2ce3d23)

**Comment by D-Aman-S** [comment]
Please assign me this issue, it should be a quick fix.Thankyou

**Comment by MihirCharan42** [comment]
Hi i would like to work on this issue as well, could you please assign this to me? I am GSSoC'2023 participant
