### ISSUE TITLE
Making Contributors Section Dynamic

### ISSUE THREAD

**Issue by D-Aman-S** [Clueless-Community/Spectrum-UI#151]
Currently, the contributor's section is hardcoded and thus not very useful, making it dynamic by leveraging publically available GitHub APIs should do the trick.
![image](https://github.com/Clueless-Community/Spectrum-UI/assets/75574963/5e36c08f-0473-4b06-a34e-6a80a0681e77)

**Comment by D-Aman-S** [comment]
if you could assign me this issue it would be of great help.The contributors have worked very hard and thus properly crediting them is the only right

**Comment by ashdude1401** [comment]
@D-Aman-S you assign this issue .Go for it .

**Comment by D-Aman-S** [comment]
hello I have fixed the issue, here's the PR for it-https://github.com/Clueless-Community/Spectrum-UI/pull/158
Any further guidance regarding code quality, etc are much Welcomed

**Comment by D-Aman-S** [comment]
hello @ashdude1401 ,i had one doubt, I am a bit new to git. So I forgot to create a branch from my fork when working on this issue, now since I have resolved it, I want to work on another issue but my main branch still contains changes from the previous issue a.Is there any workaround to it?

**Comment by BrawlerXull** [comment]
> hello @ashdude1401 ,i had one doubt, I am a bit new to git. So I forgot to create a branch from my fork when working on this issue, now since I have resolved it, I want to work on another issue but my main branch still contains changes from the previous issue a.Is there any workaround to it?


first make sure to sync your forked repo with original 
try command 'git pull' to pull the main branch from your forked repo to your local pc
then create a new branch 'git checkout new-branch-name'
do changes in file and use 'git add .'
commit the changes by 'git commit -m "title of the commit"
push the commit to your forked repo by 'git push origin branch-name'

**Comment by D-Aman-S** [comment]
Thankyou @ashdude1401 it worked like a charm
