### ISSUE TITLE
Adding copy functionality to the button in about page 

### ISSUE THREAD

**Issue by BrawlerXull** [Clueless-Community/Spectrum-UI#152]
<img width="1440" alt="Screenshot 2023-05-20 at 2 49 38 PM" src="https://github.com/Clueless-Community/Spectrum-UI/assets/111864031/6042559d-163d-48b9-8dee-9798ecf167eb">

Currently we can't copy the link when we click on the copy button please assign me the issue so that I can make the button work and make it look good

**Comment by Uttkarsh-raj** [comment]
hii @ashdude1401  I would like to work on this issue.. can you assign this to me..

**Comment by BrawlerXull** [comment]
@ashdude1401 @Debajyoti14  
hey the issue is solved by #160

https://github.com/Clueless-Community/Spectrum-UI/assets/111864031/5bb9625b-ed82-4919-aaf8-307e783163c2

Please compare and give feedback for improvement UI/ enhancement in the functionality
