### ISSUE TITLE
Splash screen size issue

### ISSUE THREAD

**Issue by BrawlerXull** [Clueless-Community/Spectrum-UI#153]
Enhancing the splash screen ui

Problem - A white line is appearing on the right side

Before I fixed 
<img width="1440" alt="Screenshot 2023-05-20 at 2 59 39 PM" src="https://github.com/Clueless-Community/Spectrum-UI/assets/111864031/2eb0b965-e789-4048-aec8-ce467b6d29a0">

After I fixed
<img width="1440" alt="Screenshot 2023-05-20 at 3 01 14 PM" src="https://github.com/Clueless-Community/Spectrum-UI/assets/111864031/1db029aa-09ed-49ff-b9e0-c527364fb9ae">

**Comment by BrawlerXull** [comment]
Please assign me the issue so that I can work on it and submit a pr

**Comment by Apreksha** [comment]
Hello. I'm a GSSoC'23 contributor. I want to fix splash screen size issue. Could you please assign me this task.

**Comment by ashdude1401** [comment]
@BrawlerXull you assigned this issue, make the splash screen responsive .

**Comment by AMAN-BAGADIYA** [comment]
> Hello, I'm a contributor to GSSOC'23 I am very much Interested in contributing to this project .I am Skilled in web development and I am ready to collaborate and follow all project guidelines.
> I will try to make it as different as possible and exciting also.
> Please assign it to me. Thank you in advance.😇

**Comment by BrawlerXull** [comment]
> @BrawlerXull you assigned this issue, make the splash screen responsive .

Hey the issue is solved by #159 please compare and give feedback if any changes req
I have removed scaffold area just because if was not contributing the ui in a positive Manner
The new UI looks like this
<img width="1440" alt="Screenshot 2023-05-20 at 11 26 36 PM" src="https://github.com/Clueless-Community/Spectrum-UI/assets/111864031/83766f13-a21a-4792-ab39-ae50e1f67622">
