### ISSUE TITLE
Overflow Issue in Card Component

### ISSUE THREAD

**Issue by Deepanshu-Sharma-18** [Clueless-Community/Spectrum-UI#154]
Overflow Bug in lib/ui_components/cards/All Cards/blog_card/card_2.dart: Blog Card #2 experiences an overflow problem, causing content spillage. Fix needed for proper display and layout.
![Screenshot 2023-05-20 184825](https://github.com/Clueless-Community/Spectrum-UI/assets/67851435/cc729e10-4a70-4520-b11e-da6135281ae0)

**Comment by Deepanshu-Sharma-18** [comment]
Can I work on this issue?

**Comment by ashdude1401** [comment]
Actually , this issue has been already raised by someone else and he is assigned this issue .You can find some other bug in in app or do some enhancement.

**Comment by Deepanshu-Sharma-18** [comment]
okay, Sorry for the repeated issue

**Comment by ashdude1401** [comment]
> okay, Sorry for the repeated issue

No issue . You can find some other issue .
