### ISSUE TITLE
Icon Change on Expansion of Details Component

### ISSUE THREAD

**Issue by Deepanshu-Sharma-18** [Clueless-Community/Spectrum-UI#156]
Changing Icon when the Card is expanded to inverse of drop down button.

![Screenshot 2023-05-20 205900](https://github.com/Clueless-Community/Spectrum-UI/assets/67851435/7a03806a-4ca7-4d94-8ee2-b95544d02f98)
![Screenshot 2023-05-20 205913](https://github.com/Clueless-Community/Spectrum-UI/assets/67851435/1f46efa2-9454-4f67-89bc-2dfc5fb31db0)

**Comment by Deepanshu-Sharma-18** [comment]
Can I work on this quick?

**Comment by Gitesg** [comment]
i  want to work on it.

**Comment by ashdude1401** [comment]
@Deepanshu-Sharma-18, could you please provide additional information about your Pull Request? It would be helpful to have a more detailed explanation of what you are planning to do. When creating a Pull Request, it's essential to provide a comprehensive explanation of your proposed changes, including the purpose, expected outcomes, and any relevant context.

Additionally, it's advisable to include full screenshots whenever possible. Visual aids can greatly assist in understanding the changes you are suggesting. They provide clarity and help ensure that the proposed modifications align with the overall design and functionality of the app.

Thank you for your understanding and cooperation. If you have any further questions or need assistance, feel free to ask.

Best regards,
Ashutosh Jha
Spectrum UI

**Comment by Deepanshu-Sharma-18** [comment]
Yeah, 
Firstly sorry for the inconvenience 

I was thinking of changing the arow down icon to arrow up icon when the details screen is expanded/clicked.




Before : Notice the Icon beside Details button is arrow down.
![Screenshot 2023-05-20 223632](https://github.com/Clueless-Community/Spectrum-UI/assets/67851435/b881e2c5-f1f7-458d-9c13-e3ba9d540520)

After : Notice the Icon here is arrow up.
![Screenshot 2023-05-20 223544](https://github.com/Clueless-Community/Spectrum-UI/assets/67851435/485ec8ec-92d8-4350-b6a0-b216f6ebd616)

**Comment by ashdude1401** [comment]
@Deepanshu-Sharma-18  got your point .You have been assigned this issue.

**Comment by piyushkumar12111111** [comment]
Please assign this issue to me
