### ISSUE TITLE
Adding good READ.me file to this repository 

### ISSUE THREAD

**Issue by Abhinavcode13** [Clueless-Community/Spectrum-UI#162]

**Comment by Abhinavcode13** [comment]
Assign this issue to me under gssoc23 @ashdude1401 will make sure readme file contains all the important info and good UI

**Comment by ashdude1401** [comment]
@Abhinavcode13 can you give me more info how exactly you are going to improve the readme , like what are changes or new thing you will add on .

**Comment by Abhinavcode13** [comment]
Additions that will be done in the readme file will be :

Include step-by-step instructions on how to set up and install the project. Specify any dependencies, libraries, or frameworks required, along with the commands or procedures needed to install them.

If the project requires any configuration files or settings, explain how to modify and customize them

Explain the preferred workflow for submitting bug reports, feature requests, or pull requests.

Consider adding badges or shields to your README file to provide quick visual information about the project.

Acknowledge and give credit to any individuals, libraries, or projects that have influenced or contributed to your project

If the project has a defined color palette or typography, mention and showcase them in the README.

If you have received positive user feedback or testimonials about the project's design or usability, feature them in the README to build credibility and demonstrate the project's value.

@ashdude1401  please check this !!

**Comment by Abhinavcode13** [comment]
Can you assign me this issue now @ashdude1401 .

**Comment by Debajyoti14** [comment]
@Abhinavcode13 Assigning this to you

**Comment by Abhinavcode13** [comment]
hello @Debajyoti14 can you just brief about the repository!!

**Comment by Debajyoti14** [comment]
@Abhinavcode13 There is already a more than decent readme in the repository. All information are there

**Comment by Abhinavcode13** [comment]
Cool then will merge PR by EOD @Debajyoti14
