### ISSUE TITLE
 adding radial slider and animated slider or circular  slider in slider section

### ISSUE THREAD

**Issue by Gitesg** [Clueless-Community/Spectrum-UI#164]
i am gssoc23 contributor  i want to work on this feature @ashdude1401 should i work on?

**Comment by ashdude1401** [comment]
@Gitesg Can you please give more info regarding changes that you want make .

**Comment by Gitesg** [comment]
, the user interface consists of a circular slider with a blue progress color. The slider represents a value ranging from 0% to 100%. The current value is displayed in the center of the slider. When the slider crosses the 75% mark, the color changes to red. The slider can be interacted with by dragging or pan


[device-2023-05-21-092031.webm](https://github.com/Clueless-Community/Spectrum-UI/assets/105045980/8ef5920a-2670-4e50-baf7-fed24acd828f)

![Screenshot_20230521_092151](https://github.com/Clueless-Community/Spectrum-UI/assets/105045980/abb1511b-4814-4011-a8be-4f9d91fcd5aa)

**Comment by Gitesg** [comment]
if u  like this then assign me this feature.

**Comment by Saksham0205** [comment]
can you please assign me this issue under GSSoc 2023. I really want to work on this issue.

**Comment by Amna-Yasir** [comment]
can you assign me this task. I will do it

**Comment by ashdude1401** [comment]
Currently we are not assigning any design related issues as were are working on app design .After it get's completed we will raising issue regarding that .So, I am closing this issue , till then you can find some other bug or enhancement in the app .
