### ISSUE TITLE
Adding more type of button in button section 

### ISSUE THREAD

**Issue by piyushkumar12111111** [Clueless-Community/Spectrum-UI#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by piyushkumar12111111** [comment]
![1684648338](https://github.com/Clueless-Community/Spectrum-UI/assets/103259442/013e6e60-8fca-440d-b8a2-3e4ca03c4654)

**Comment by Debajyoti14** [comment]
@piyushkumar12111111 We will be coming up with new button designs within 2-3 days. Wait till then

**Comment by ashdude1401** [comment]
Currently we are not assigning any design related issues as were are working on app design .After it get's completed we will raising issue regarding that .So, I am closing this issue , till then you can find some other bug or enhancement in the app .
