### ISSUE TITLE
More Buttons 

### ISSUE THREAD

**Issue by Aditya01237** [Clueless-Community/Spectrum-UI#167]
We can add a toggle button in button section. 
![Screenshot 2023-05-21 135002](https://github.com/Clueless-Community/Spectrum-UI/assets/80575917/f5042c90-3607-4885-bed4-34e7e65cef9b)

**Comment by Aditya01237** [comment]
Assign this as my first GSSOC issue

**Comment by YuvrajSingh3110** [comment]
Hey! We can add some buttons with both icon and text like this :-

![Screenshot 2023-05-21 170407](https://github.com/Clueless-Community/Spectrum-UI/assets/96365625/7b547434-3249-44ed-97a6-b63d42a3388f)

Assign this issue to me

**Comment by piyushkumar12111111** [comment]
Assign this issue to me

**Comment by Khushal747** [comment]
please assign me this issue under GSSOC'23

**Comment by ashdude1401** [comment]
Currently we are not assigning any design related issues , as were are working on app design .After it get's completed we will raising issue regarding the same .So, I am closing this issue  , till then you can find some other bug or enhancement in the app .
