### ISSUE TITLE
Adding a new scrollable component to the library [GSSOC'23]

### ISSUE THREAD

**Issue by Vidhish-Trivedi** [Clueless-Community/Spectrum-UI#168]
## Aim
- To add a new widget to the UI library.
- This would be a scrollable component which can be used to display a list of objects.

## Why add this?
- Having lists displayed on the entire page height pushes the other components such as buttons, which should have been easily accessible, down.
- - Using a scrollable component, this issue can be resolved.

## Additional Note
- This issue has been opened as part of GSSOC'23, please make note of the same.

**Comment by dev-abir** [comment]
Flutter already has such a widget. This UI library should customize it to match other widgets' design.
Suggest some ideas? I want to work on this, assign me.

**Comment by abhinav52000** [comment]
I Will like to resolve this issue can you assign it to me 
And can you add me to this project as collaborator?

**Comment by Vidhish-Trivedi** [comment]
Hi, I too am a contributor and have opened this issue so that I can work on it.

**Comment by chiki012** [comment]
hello, I have already worked on this kind of thing. I'm good to solve this issue.

**Comment by shubham725809** [comment]
I can develop this with a smooth UI,so please assign me this

**Comment by Debajyoti14** [comment]
@dev-abir @Vidhish-Trivedi @abhinav52000 Suggest some design inspirations on which you are going to work
