### ISSUE TITLE
BUG : UI component in readme file directs to nothing

### ISSUE THREAD

**Issue by Abhinavcode13** [Clueless-Community/Spectrum-UI#169]
please assign this issue to me @ashdude1401 @Debajyoti14

**Comment by PravanshuSamadhiya** [comment]
Hey @Debajyoti14 can you please assign this issue to me

**Comment by Debajyoti14** [comment]
@Abhinavcode13 Where exactly are you going to redirect to?

**Comment by Khushal747** [comment]
I would like to work in this issue under GSSOC'23 ,please assign me this issue.
