### ISSUE TITLE
Bottom Overflow in Inbox Messages[GSSoC'23]

### ISSUE THREAD

**Issue by AnubhaSharma2709** [Clueless-Community/Spectrum-UI#170]
When we open the Messages tab their is bottom overflow by 1.7 pixels. The code is not responsive
Under GSSoC'23

**Comment by Khushal747** [comment]
please assign me this issue under GSSOC'23

**Comment by AnubhaSharma2709** [comment]
> @AnubhaSharma2709 assigning you

Thankyou so much ! Working on the same
