### ISSUE TITLE
Improvement in Blog Cards [GSSoC'23]

### ISSUE THREAD

**Issue by AnubhaSharma2709** [Clueless-Community/Spectrum-UI#172]
The UI of Blog Cards can be improved
under GSSoC'23

**Comment by tusharv01** [comment]
hi, @AnubhaSharma2709 please assign me this issue under gssoc 23 as my skills are aligned to do this issue.

**Comment by ETHER-BHASHI** [comment]
I would like to add the scores of particular test. May you please assign this task to me.

**Comment by shubham725809** [comment]
I can develop this with a better UI that is user-friendly.

**Comment by chiki012** [comment]
Hello, I'm good in frontend. and I can easily solve this issue.

**Comment by Roshaen** [comment]
@AnubhaSharma2709 do you want to take up this issue?

**Comment by AnubhaSharma2709** [comment]
> @AnubhaSharma2709 do you want to take up this issue?

Hey currently I am working on Price Cards. My exams were going on hence my speed was a bit slow but if you feel that you want to have a faster pace then you may allot it to someone else
