### ISSUE TITLE
Creating an add to favorites button and the result is added to the favorites screen.

### ISSUE THREAD

**Issue by Uttkarsh-raj** [Clueless-Community/Spectrum-UI#174]
**Is your feature request related to a problem? Please describe.**
Currently there is no such way of adding the widgets to favorites or saving them for later.

**Describe the solution you'd like**
I would like to integrate state management using providers so that we can easily star the widgets for later. 

**Additional context**
I have already tried implementing this feature and the screenshots are provided.

![Screenshot (2)](https://github.com/Clueless-Community/Spectrum-UI/assets/106571927/3cd7082e-dedc-4226-a443-63ed716d4167)
![Screenshot (3)](https://github.com/Clueless-Community/Spectrum-UI/assets/106571927/96718781-cf0b-4741-905d-7b12b323be38)

**Comment by Uttkarsh-raj** [comment]
@ashdude1401  please assign the issue to me as i have already tried a way out for this..

**Comment by Debajyoti14** [comment]
@Uttkarsh-raj There are some primary issues with the Add to Favourite Feature. As It's stored in the state, The state will not persist when the app is closed. Then there is no meaning of Add to Favourites Feature.

**Comment by Uttkarsh-raj** [comment]
> @Uttkarsh-raj There are some primary issues with the Add to Favourite Feature. As It's stored in the state, The state will not persist when the app is closed. Then there is no meaning of Add to Favourites Feature.

Hey i checked it and realized that this is a issue that can be solved easily using storing data in the  local storage . I can work on this issue can you create an issue and assign me this...

**Comment by Debajyoti14** [comment]
@Uttkarsh-raj Yup create an issue and i'll assign you. What local database you'll use?

**Comment by Uttkarsh-raj** [comment]
> @Uttkarsh-raj Yup create an issue and i'll assign you. What local database you'll use?

I am thinking of using hive...

**Comment by Uttkarsh-raj** [comment]
@Debajyoti14 I have a solution but i would like to discuss it once ....

**Comment by Debajyoti14** [comment]
@Uttkarsh-raj Dm me on discord

**Comment by Uttkarsh-raj** [comment]
@Debajyoti14 hey can you check your dm....

**Comment by Uttkarsh-raj** [comment]
@Debajyoti14  I think this issue is solved and i think it was a level 3 issue.... You can close it and can you add the same label to my pr made regarding this issue.. i guess it was merged but still... moreover i would like to know what are the current preferred things you would want in the app so that i can try to work on that ... thanks...

**Comment by Uttkarsh-raj** [comment]
@Debajyoti14  There is a slight change in this feature that i would like to propose . Currently, the star icon becomes yellow on tapping i.e. it is a boolean logic , but now since we have local storage access we make make it like if the widgets index is present in the list then the star will be yellow and like this we can even save the state of this icon without making any major changes to the codebase. And i think with this enhancement this issue will get fully solved......Thanks for the appreciation.
