### ISSUE TITLE
Adding Radio Widget card with UIs

### ISSUE THREAD

**Issue by helloamj** [Clueless-Community/Spectrum-UI#181]
### Adding Radio Widget Present

@Debajyoti14 Could u please assign it to me sir

**Comment by Roshaen** [comment]
Assigning @helloamj

**Comment by helloamj** [comment]
@Roshaen sir can you specify the conflict in merging it

**Comment by helloamj** [comment]
@Roshaen just resolved the conflicts now you can merge it

**Comment by Roshaen** [comment]
Thanks, @helloamj 
Your pr is merged
Closing this issue
