### ISSUE TITLE
Title of the buttons 

### ISSUE THREAD

**Issue by VISHALGUPTA100803** [Clueless-Community/Spectrum-UI#184]
Title of every button should be at centre it is bottom left aligned.
Assign me this issue i can fix this ! 
![Screenshot (632)](https://github.com/Clueless-Community/Spectrum-UI/assets/96491059/f8de80f7-d408-4d20-8461-f89af4fbb987)

**Comment by VISHALGUPTA100803** [comment]
@Debajyoti14 please assign this to me

**Comment by Debajyoti14** [comment]
@VISHALGUPTA100803 No this is the design we have gone with.
With centre align it will not look that good.
So closing this issue
