### ISSUE TITLE
Adding the search feature in the project

### ISSUE THREAD

**Issue by Uttkarsh-raj** [Clueless-Community/Spectrum-UI#186]
**Is your feature request related to a problem? Please describe.**
Currently there is no such method to search for the widgets you are trying to search for.

**Describe the solution you'd like**
Converting the widgets to a list and then searching for the search controller keyword and if it matches add to results.

**Additional context**
I have tried to implement it and i have a basic design on how to implement it.
![Screenshot 2023-05-24 130932](https://github.com/Clueless-Community/Spectrum-UI/assets/106571927/4e9b84a7-9eff-4fad-bc79-535e6d7221b6)

**Comment by Uttkarsh-raj** [comment]
I would like to solve this issue. Please assign this to me.

**Comment by ashdude1401** [comment]
@Uttkarsh-raj you have been assign this issue.

**Comment by Uttkarsh-raj** [comment]
@ashdude1401 made the pr please review it...
