### ISSUE TITLE
To add icons in button category widgets

### ISSUE THREAD

**Issue by ombhojane** [Clueless-Community/Spectrum-UI#202]
Issue : 
On main screen, there are no supportive icons. User might get difficulty in understanding by text.
![image](https://github.com/Clueless-Community/Spectrum-UI/assets/82753658/b758b762-7036-4724-ab58-23e7a0d23a88)

Proposed Solution :
Let's add respective icons above the text, such that user can get more clarity about specific button widget.

List of some icons : 
![image](https://github.com/Clueless-Community/Spectrum-UI/assets/82753658/3228275c-7a29-4bd0-966a-c0a8cf2169b0)
![image](https://github.com/Clueless-Community/Spectrum-UI/assets/82753658/f9fc8661-3e58-427f-b67a-acbd33d3fea5)
![image](https://github.com/Clueless-Community/Spectrum-UI/assets/82753658/4e63f4a9-9e29-47ea-b0f8-130f590e7634)

Can you please assign this issue to me..
GSSOC 2023 :)

**Comment by ashdude1401** [comment]
Currently we are not assigning any design related pr as were are working on app design .After it get's completed we will raising issue regarding that .So, I am closing this pr , till then you can find some other bug or enhancement in the app .

**Comment by ashdude1401** [comment]
Currently we are not assigning any design related pr as were are working on app design .After it get's completed we will raising issue regarding that .So, I am closing this pr , till then you can find some other bug or enhancement in the app .
