### ISSUE TITLE
Adding checkboxes

### ISSUE THREAD

**Issue by BhavaniSaranga12** [Clueless-Community/Spectrum-UI#204]
There is a empty checkbox folder in the project, So I want add different checkboxes to it. Here is an example
![checkbox](https://github.com/Clueless-Community/Spectrum-UI/assets/117339714/c5bbfca5-5db7-4e0d-ac6f-90280901aa6f)

**Comment by ashdude1401** [comment]
Can you give more context about your issue ?

**Comment by BhavaniSaranga12** [comment]
There is a empty checkbox folder, so I want to add different checkboxes. Here is an example 
![checkbox](https://github.com/Clueless-Community/Spectrum-UI/assets/117339714/adc2db72-9815-45bc-b902-f798f308e84f)
