### ISSUE TITLE
Dark Theme Card Overflow

### ISSUE THREAD

**Issue by ZapeeoSheikh** [Clueless-Community/Spectrum-UI#215]
**Describe the bug**

**To Reproduce**
1. Go to 'lib folder'
2. Click on 'card_6.dart'
3. Scroll down to 'line 70'

**Expected behavior**

**Screenshots**
<img width="1440" alt="error" src="https://github.com/Clueless-Community/Spectrum-UI/assets/77886136/df50c1ff-cb94-472e-bd9e-cb8e6a96e6dc">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Khushal747** [comment]
I am interested to work on this issue please assign me this task as a GSSoC23 contributor

**Comment by ZapeeoSheikh** [comment]
@Khushal747 This issue has been resolved

**Comment by ZapeeoSheikh** [comment]
@Roshaen Please add gssoc23 label here
