### ISSUE TITLE
 Snackbar Text Visibility Issue in Dark Mode on About Page

### ISSUE THREAD

**Issue by ashdude1401** [Clueless-Community/Spectrum-UI#224]
On the About page of our GitHub repository, when copying the repository link to the clipboard, a bottom snackbar appears with text that is not visible in dark mode. This creates a usability issue as users are unable to read the text displayed in the snackbar.

Expected Behavior:
The text in the snackbar should be visible and easily readable, even in dark mode. It should have sufficient contrast with the background to ensure optimal visibility.

Steps to Reproduce:

On the phone dark mode.
Navigate to the About page.
Copy the repository link.
Observe the bottom snackbar and notice the lack of text visibility.
Suggested Solution:
Apply appropriate styling to the snackbar component, ensuring that the text color in dark mode provides sufficient contrast for clear visibility.

ScreenShot:
![image](https://github.com/Clueless-Community/Spectrum-UI/assets/98846260/9f3f7e2f-c94c-4c7a-9caa-3773773a70e6)

**Comment by MihirCharan42** [comment]
Please assign me this issue, I am a GSSOC'23 participant and would love to work on this issue

**Comment by ashdude1401** [comment]
Sorry,this issue has been already taken care by @BhavaniSaranga12 .
