### ISSUE TITLE
Storing data of the fav widgets locally to save it and load it on starting the app. 

### ISSUE THREAD

**Issue by Uttkarsh-raj** [Clueless-Community/Spectrum-UI#233]
**Is your feature request related to a problem? Please describe.**
Currently the starred widgets are lost since the state is lost on startup.

**Describe the solution you'd like**
Mapping the widgets to indexes and storing the indexes and building widgets from it.

**Describe alternatives you've considered**
I have considered storing widget data directly but it was not possible.

**Additional context**
It is related to the star the widget feature.

**Comment by Uttkarsh-raj** [comment]
@Debajyoti14 hey i was able to find a solution while preventing any major change to the code base. It took time but i am ready to make a pr . Please assign me this issue.

**Comment by Debajyoti14** [comment]
@Uttkarsh-raj Assigned you
