### ISSUE TITLE
Addition of dependabot.yml file

### ISSUE THREAD

**Issue by DivyanshiNarang** [Clueless-Community/Spectrum-UI#250]
We need to add dependabot.yml file as it helps us to keep our dependencies up to date. Every day, it checks your dependency files for outdated requirements and opens individual PRs for any it finds.

@Roshaen please assign me this issue under gssoc'23.

**Comment by Drishtianand19** [comment]
@Roshaen please assign me this issue would love to work on it.

**Comment by Roshaen** [comment]
@DivyanshiNarang assigned it

**Comment by DivyanshiNarang** [comment]
Hello, @Roshaen please give level and gssoc23 label to this PR.
