### ISSUE TITLE
[App UI] Create the whole App UI

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#76]
Refer to the Figma link for the design
https://www.figma.com/file/5qmXvL7Dm3v2pHi12FWnNe/Untitled?node-id=0%3A1&t=8uVFwLwLdM0rv3Hz-0

**Comment by Roshaen** [comment]
Sure @Akashsri3bi

**Comment by Akashsri3bi** [comment]
@Roshaen please group all the elipses in splash screen or I can do that if you provide edit access

**Comment by Roshaen** [comment]
@Akashsri3bi its done

**Comment by Akashsri3bi** [comment]
Thanks @Roshaen
