### ISSUE TITLE
[Input Fields] Create interactive input fields

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#79]
Figma link:
https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=140%3A40490&t=8uVFwLwLdM0rv3Hz-1

**Comment by cschinmay777** [comment]
I am interested on working on this.

**Comment by Roshaen** [comment]
Assigned @cschinmay777

**Comment by Roshaen** [comment]
This issue is still open 
Some UI Changes are required

**Comment by cschinmay777** [comment]
Will you please tell what changes I have to make?

**Comment by Roshaen** [comment]
Changes Required :
1. Padding between components
2. Title of the page
3. Error validation

**Comment by RunTerror** [comment]
please assgin me this issue

**Comment by Roshaen** [comment]
ok
Assigning you @RunTerror

**Comment by RunTerror** [comment]
can u please tell me specific changes

**Comment by RunTerror** [comment]
please tell me in little detail so that i can make it fast

**Comment by RunTerror** [comment]
@Roshaen can u please tell me what changes how i have to do

**Comment by Roshaen** [comment]
these changes @RunTerror 

> Changes Required :
> 
> 1. Padding between components
> 2. Title of the page
> 3. Error validation

**Comment by RunTerror** [comment]
what is error validation
