### ISSUE TITLE
[Media Player] Create functional media player UI

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#80]
Figma link:
https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=7%3A7178&t=8uVFwLwLdM0rv3Hz-1

**Comment by Abhishek-K-Choudhary** [comment]
I want to work on this issue under JWOC

**Comment by Roshaen** [comment]
Sure @Abhishek-K-Choudhary 
Assigning you
