### ISSUE TITLE
[Pricing Cards UI] Create customizable pricing cards UI

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#81]
Figma Link:
https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=221%3A13581&t=8uVFwLwLdM0rv3Hz-1

**Comment by superiorsd10** [comment]
I'm interested in working on this. Can you please assign it to me?

**Comment by Roshaen** [comment]
Assigning @superiorsd10

**Comment by Gun2902** [comment]
can u assign me this isssue
