### ISSUE TITLE
[Messages] Create message UI components

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#82]
Figma link:
https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=140%3A42163&t=pVZdo6TCWYtyqXgK-1

**Comment by cschinmay777** [comment]
I am interested in working on this.

**Comment by Gun2902** [comment]
can u assign me this issue

**Comment by cschinmay777** [comment]
Sorry, but I have already started working on it.
