### ISSUE TITLE
[DOC] Contribution Guidelines

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#88]
Add Contribution.md explaining the process for contributing in the project 
Also, the doc should explain the folder structure of the project

**Comment by radar101** [comment]
I would like to add content in the Contribution.md. Please assign this task to me.

**Comment by Roshaen** [comment]
Sure @radar101 go for it
But first I have to explain you the contribution process to you
Let me know if we can schedule a quick gmeet

**Comment by radar101** [comment]
Yep we can schedule it now. Sorry, for late response.

**Comment by radar101** [comment]
> Sure @radar101 go for it But first I have to explain you the contribution process to you Let me know if we can schedule a quick gmeet
Yep we can schedule it now. I messaged you on the Discord about the same.

**Comment by Code1705** [comment]
Some improvisation are required and make it a little short and add some elements to make it look appealing, please assign me under JWOC.

**Comment by Roshaen** [comment]
Sure @Code1705 go for it
Assigning you

**Comment by Roshaen** [comment]
Its already assigned to @Code1705
