### ISSUE TITLE
[Component] Create card designes

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/Spectrum-UI#91]
Figma link:
https://www.figma.com/file/JPcD0ljV8yyfLBnzkiqMVc/Flutter-UI-Component?node-id=222%3A13322&t=8w362ku2O54w0UeX-1

**Comment by Subrata-Rajak** [comment]
Hey @Roshaen, I am Subrata Rajak, a participant of JWOC 23, I am looking forward to contributing to some great flutter or app dev projects and I find this repo a very good one.
can you assign me the task, please
and I have to design all the card components, shown in the design right??

**Comment by utkarsh006** [comment]
@Roshaen Can you assign this issue under JWOC.  I can contribute some card designs along with @Subrata-Rajak

**Comment by Roshaen** [comment]
Hello @Subrata-Rajak 
Yes you have to build all the cards
Assigning you

**Comment by Subrata-Rajak** [comment]
> Hello @Subrata-Rajak Yes you have to build all the cards Assigning you

Thanks for assigning me, on it

**Comment by Roshaen** [comment]
> @Roshaen Can you assign this issue under JWOC. I can contribute some card designs along with @Subrata-Rajak

Is it ok for you @Subrata-Rajak ?

**Comment by Subrata-Rajak** [comment]
@Roshaen I already finished 2 of the cards and the other components are there to develop I think he can contribute there

**Comment by Roshaen** [comment]
Cool
Then let us know which card you have made
Rest will be taken care by @utkarsh006

**Comment by Subrata-Rajak** [comment]
i have done first two so far

**Comment by RunTerror** [comment]
Please assign me this issue

**Comment by radar101** [comment]
I want to work for under this issue as a part of JWOC.

**Comment by ashdude1401** [comment]
@RunTerror you have been assigned this issue

**Comment by RunTerror** [comment]
![Screenshot_1678185721](https://user-images.githubusercontent.com/113206442/22339
![Screenshot_1678185738](https://user-images.githubusercontent.com/113206442/223399881-cea7242d-ba1a-4dc7-b91f-8ddb1f977b4e.png)
9775-407446fd-f5c4-4b43-9719-3e2121118a77.png)
hey @ashdude1401 sorry for working late i have created all 8 cards should i make more changes or create a pr

**Comment by ashdude1401** [comment]
No problem , create a  pr I will check if there is any issue .

**Comment by RunTerror** [comment]
i have created pr please check it

**Comment by RunTerror** [comment]
will i create a pr for this

**Comment by RunTerror** [comment]
![Screenshot_1678440942](https://user-images.githubusercontent.com/113206442/224474477-3a04b5d1-3d5b-4387-a30b-fc8441faafc7.png)
![Screenshot_1678440929](https://user-images.githubusercontent.com/113206442/224474482-1bcb0c40-5b2c-48dd-920a-ed279a534ee0.png)

**Comment by RunTerror** [comment]
do i have to make more changes
